package com.beecareanywhere.ui

import com.beecareanywhere.data.Settings

data class UiStrings(
    val appTitle: String,
    val settings: String,
    val back: String,
    val modelDownload: String,
    val reset: String,
    val textPlaceholder: String,
    val imageAttached: String,
    val audioAttached: String,
    val removeImage: String,
    val removeAudio: String,
    val photo: String,
    val record: String,
    val stop: String,
    val diagnose: String,
    val cancel: String,
    val describePhotoTitle: String,
    val describePhotoBody: String,
    val modelNotLoaded: String,
    val loadingModel: String,
    val modelReady: String,
    val modelErrorPrefix: String,
    val cameraPermissionDenied: String,
    val microphonePermissionDenied: String,
    val responseLanguage: String,
    val responseLanguageDescription: String,
    val uiLanguageDescription: String,
    val model: String,
    val loading: String,
    val filename: String,
    val installed: String,
    val yes: String,
    val no: String,
    val size: String,
    val path: String,
    val pinnedSha: String,
    val noneVerificationSkipped: String,
    val stubModelActive: String,
    val deleteModelFile: String,
    val about: String,
    val version: String,
    val repository: String,
    val deleteModelTitle: String,
    val deleteModelBody: String,
    val delete: String,
)

fun strings(language: Settings.Language): UiStrings = when (language) {
    Settings.Language.Swahili -> UiStrings(
        appTitle = "BeeCare Popote",
        settings = "Mipangilio",
        back = "Rudi",
        modelDownload = "Pakua modeli",
        reset = "Anza upya",
        textPlaceholder = "Eleza unachoona kwenye mzinga...",
        imageAttached = "Picha imeambatishwa",
        audioAttached = "Sauti imeambatishwa",
        removeImage = "Ondoa picha",
        removeAudio = "Ondoa sauti",
        photo = "Picha",
        record = "Rekodi",
        stop = "Simamisha",
        diagnose = "Tambua",
        cancel = "Ghairi",
        describePhotoTitle = "Eleza picha kabla ya utambuzi",
        describePhotoBody = "Taja kinachoonekana: nyuki wako au wadudu, nyuki waliokufa, utando, siafu, hali ya hewa, na kama wanaruka sana au wamejikusanya sehemu moja.",
        modelNotLoaded = "Modeli haijapakiwa",
        loadingModel = "Inapakia modeli...",
        modelReady = "Modeli iko tayari",
        modelErrorPrefix = "Hitilafu ya modeli: ",
        cameraPermissionDenied = "Ruhusa ya kamera imekataliwa",
        microphonePermissionDenied = "Ruhusa ya kipaza sauti imekataliwa",
        responseLanguage = "Lugha ya programu na majibu",
        responseLanguageDescription = "Chagua lugha ya maandishi ya programu na majibu ya modeli.",
        uiLanguageDescription = "Majina ya vitufe na maswali yatafuata lugha hii.",
        model = "Modeli",
        loading = "Inapakia...",
        filename = "Jina la faili",
        installed = "Imewekwa",
        yes = "ndiyo",
        no = "hapana",
        size = "Ukubwa",
        path = "Mahali",
        pinnedSha = "SHA-256 iliyowekwa",
        noneVerificationSkipped = "(hakuna - uthibitisho umerukwa)",
        stubModelActive = "Modeli ya majaribio inatumika - LiteRT-LM itawekwa awamu inayofuata",
        deleteModelFile = "Futa faili ya modeli",
        about = "Kuhusu",
        version = "Toleo",
        repository = "Hazina",
        deleteModelTitle = "Futa faili ya modeli?",
        deleteModelBody = "Utahitaji kupakua modeli tena kabla ya kufanya utambuzi.",
        delete = "Futa",
    )
    else -> UiStrings(
        appTitle = "BeeCare Anywhere",
        settings = "Settings",
        back = "Back",
        modelDownload = "Model download",
        reset = "Reset",
        textPlaceholder = "Describe what you're seeing in the hive...",
        imageAttached = "Image attached",
        audioAttached = "Audio attached",
        removeImage = "Remove image",
        removeAudio = "Remove audio",
        photo = "Photo",
        record = "Record",
        stop = "Stop",
        diagnose = "Diagnose",
        cancel = "Cancel",
        describePhotoTitle = "Describe the photo before diagnosis",
        describePhotoBody = "Tell BeeCare what is visible: your bees or pests, dead bees, webbing, ants, weather, and whether they are flying heavily or mostly clustered.",
        modelNotLoaded = "Model not loaded",
        loadingModel = "Loading model...",
        modelReady = "Model ready",
        modelErrorPrefix = "Model error: ",
        cameraPermissionDenied = "Camera permission denied",
        microphonePermissionDenied = "Microphone permission denied",
        responseLanguage = "App and response language",
        responseLanguageDescription = "Choose the language used for app text and model responses.",
        uiLanguageDescription = "Buttons, prompts, and model guidance follow this language.",
        model = "Model",
        loading = "Loading...",
        filename = "Filename",
        installed = "Installed",
        yes = "yes",
        no = "no",
        size = "Size",
        path = "Path",
        pinnedSha = "Pinned SHA-256",
        noneVerificationSkipped = "(none - verification skipped)",
        stubModelActive = "Stub model active - Phase 2 swaps in LiteRT-LM",
        deleteModelFile = "Delete model file",
        about = "About",
        version = "Version",
        repository = "Repository",
        deleteModelTitle = "Delete model file?",
        deleteModelBody = "You'll need to download the model again before running diagnostics.",
        delete = "Delete",
    )
}
