package com.beecareanywhere.ui

import com.beecareanywhere.data.Settings

data class UiStrings(
    // App shell
    val appTitle: String,
    val settings: String,
    val back: String,
    val modelDownload: String,
    val reset: String,
    val cancel: String,
    val yes: String,
    val no: String,
    val loading: String,

    // HomeScreen
    val greetingBeekeeper: String,
    val hivesActive: String,
    val checkOnBees: String,
    val checkOnBeesSubtitle: String,
    val start: String,
    val asante: String,
    val asanteBody: String,
    val recentCheckins: String,

    // ComposeScreen
    val newCheckin: String,
    val mascotTip: String,
    val snapAPhoto: String,
    val tapToTakePhoto: String,
    val orUploadGallery: String,
    val photoAttachedLabel: String,
    val justNow: String,
    val retake: String,
    val remove: String,
    val describeWhatYouSee: String,
    val describePlaceholder: String,
    val describeYourPhoto: String,
    val describeChips: List<String>,
    val saveDescription: String,
    val askAQuestion: String,
    val questionPlaceholder: String,
    val questionChips: List<String>,
    val exampleQuestions: String,
    val saveQuestion: String,
    val tapToAdd: String,
    val diagnose: String,

    // ChatScreen
    val beeCareDiagnosis: String,
    val runningOffline: String,
    val typeFollowUp: String,

    // Diagnostic / model state
    val textPlaceholder: String,
    val imageAttached: String,
    val audioAttached: String,
    val removeImage: String,
    val removeAudio: String,
    val photo: String,
    val record: String,
    val stop: String,
    val describePhotoTitle: String,
    val describePhotoBody: String,
    val modelNotLoaded: String,
    val loadingModel: String,
    val modelReady: String,
    val modelErrorPrefix: String,
    val cameraPermissionDenied: String,
    val microphonePermissionDenied: String,

    // SettingsScreen
    val responseLanguage: String,
    val responseLanguageDescription: String,
    val uiLanguageDescription: String,
    val model: String,
    val filename: String,
    val installed: String,
    val size: String,
    val path: String,
    val pinnedSha: String,
    val noneVerificationSkipped: String,
    val stubModelActive: String,
    val deleteModelFile: String,
    val about: String,
    val version: String,
    val repository: String,
    val deleteModelTitle: String,
    val deleteModelBody: String,
    val delete: String,
)

fun strings(language: Settings.Language): UiStrings = when (language) {
    Settings.Language.Swahili -> UiStrings(
        appTitle = "BeeCare Popote",
        settings = "Mipangilio",
        back = "Rudi",
        modelDownload = "Pakua modeli",
        reset = "Anza upya",
        cancel = "Ghairi",
        yes = "ndiyo",
        no = "hapana",
        loading = "Inapakia...",

        greetingBeekeeper = "Habari, Mfugaji wa Nyuki",
        hivesActive = "Mizinga yako ina shughuli leo.",
        checkOnBees = "Kagua nyuki wako",
        checkOnBeesSubtitle = "Piga picha au eleza unachoona. Tutakusaidia kutambua.",
        start = "Anza",
        asante = "Asante, wafugaji wa Kenya!",
        asanteBody = "Mnashika misitu ikiwa hai na mashamba yakichanua.",
        recentCheckins = "Kumbukumbu",

        newCheckin = "Kagua nyuki",
        mascotTip = "Tambua tatizo leo, epuka kundi lako kuhama kesho!",
        snapAPhoto = "Piga picha au pakia",
        tapToTakePhoto = "Bonyeza kupiga picha",
        orUploadGallery = "au pakia kutoka kwenye simu",
        photoAttachedLabel = "Picha imeambatishwa",
        justNow = "Sasa hivi",
        retake = "Badilisha",
        remove = "Ondoa",
        describeWhatYouSee = "Eleza unachoona",
        describePlaceholder = "Mfano: nyuki wengi wamekufa mlangoni, na ninaona siafu pembeni…",
        describeYourPhoto = "Eleza picha yako",
        describeChips = listOf("nyuki waliokufa", "siafu", "utando", "wanaruka sana", "mvua imenyesha", "mlangoni"),
        saveDescription = "Hifadhi",
        askAQuestion = "Uliza swali",
        questionPlaceholder = "Mfano: kwa nini wanaruka kidogo?",
        questionChips = listOf("Kwa nini wanaruka kidogo?", "Ni salama kuvuna?", "Nifanye nini sasa?", "Itachukua muda gani?"),
        exampleQuestions = "Mifano ya maswali",
        saveQuestion = "Hifadhi",
        tapToAdd = "Bonyeza kuongeza",
        diagnose = "Tambua",

        beeCareDiagnosis = "Utambuzi wa BeeCare",
        runningOffline = "Inafanya kazi nje ya mtandao · Gemma",
        typeFollowUp = "Andika ujumbe…",

        textPlaceholder = "Eleza unachoona kwenye mzinga...",
        imageAttached = "Picha imeambatishwa",
        audioAttached = "Sauti imeambatishwa",
        removeImage = "Ondoa picha",
        removeAudio = "Ondoa sauti",
        photo = "Picha",
        record = "Rekodi",
        stop = "Simamisha",
        describePhotoTitle = "Eleza picha kabla ya utambuzi",
        describePhotoBody = "Taja kinachoonekana: nyuki wako au wadudu, nyuki waliokufa, utando, siafu, hali ya hewa, na kama wanaruka sana au wamejikusanya sehemu moja.",
        modelNotLoaded = "Modeli haijapakiwa",
        loadingModel = "Inapakia modeli...",
        modelReady = "Modeli iko tayari",
        modelErrorPrefix = "Hitilafu ya modeli: ",
        cameraPermissionDenied = "Ruhusa ya kamera imekataliwa",
        microphonePermissionDenied = "Ruhusa ya kipaza sauti imekataliwa",
        responseLanguage = "Lugha ya programu na majibu",
        responseLanguageDescription = "Chagua lugha ya maandishi ya programu na majibu ya modeli.",
        uiLanguageDescription = "Majina ya vitufe na maswali yatafuata lugha hii.",
        model = "Modeli",
        filename = "Jina la faili",
        installed = "Imewekwa",
        size = "Ukubwa",
        path = "Mahali",
        pinnedSha = "SHA-256 iliyowekwa",
        noneVerificationSkipped = "(hakuna - uthibitisho umerukwa)",
        stubModelActive = "Modeli ya majaribio inatumika - LiteRT-LM itawekwa awamu inayofuata",
        deleteModelFile = "Futa faili ya modeli",
        about = "Kuhusu",
        version = "Toleo",
        repository = "Hazina",
        deleteModelTitle = "Futa faili ya modeli?",
        deleteModelBody = "Utahitaji kupakua modeli tena kabla ya kufanya utambuzi.",
        delete = "Futa",
    )
    else -> UiStrings(
        appTitle = "BeeCare Anywhere",
        settings = "Settings",
        back = "Back",
        modelDownload = "Model download",
        reset = "Reset",
        cancel = "Cancel",
        yes = "yes",
        no = "no",
        loading = "Loading...",

        greetingBeekeeper = "Hi, Beekeeper",
        hivesActive = "Your hives are busy today.",
        checkOnBees = "Check on your bees",
        checkOnBeesSubtitle = "Snap a photo or describe what you see. We’ll help you figure it out.",
        start = "Start",
        asante = "Asante, Kenyan beekeepers.",
        asanteBody = "You keep our forests alive and our shambas in bloom.",
        recentCheckins = "Recent check-ins",

        newCheckin = "New check-in",
        mascotTip = "Identify the issue today, avoid your colony absconding tomorrow!",
        snapAPhoto = "Snap a photo",
        tapToTakePhoto = "Tap to take a photo",
        orUploadGallery = "or upload from gallery",
        photoAttachedLabel = "Photo attached",
        justNow = "Just now",
        retake = "Retake",
        remove = "Remove",
        describeWhatYouSee = "Describe what you see",
        describePlaceholder = "e.g., lots of dead bees at the entrance, and I see ants on the side…",
        describeYourPhoto = "Describe your photo",
        describeChips = listOf("dead bees", "ants", "webbing", "flying heavily", "rained yesterday", "at entrance"),
        saveDescription = "Save description",
        askAQuestion = "Ask a question",
        questionPlaceholder = "e.g., why are they not flying much?",
        questionChips = listOf("Why are they not flying much?", "Is it safe to harvest?", "What should I do now?", "How long to recover?"),
        exampleQuestions = "Example questions",
        saveQuestion = "Save question",
        tapToAdd = "Tap to add",
        diagnose = "Diagnose",

        beeCareDiagnosis = "BeeCare diagnosis",
        runningOffline = "Running offline · Gemma",
        typeFollowUp = "Type a follow-up…",

        textPlaceholder = "Describe what you're seeing in the hive...",
        imageAttached = "Image attached",
        audioAttached = "Audio attached",
        removeImage = "Remove image",
        removeAudio = "Remove audio",
        photo = "Photo",
        record = "Record",
        stop = "Stop",
        describePhotoTitle = "Describe the photo before diagnosis",
        describePhotoBody = "Tell BeeCare what is visible: your bees or pests, dead bees, webbing, ants, weather, and whether they are flying heavily or mostly clustered.",
        modelNotLoaded = "Model not loaded",
        loadingModel = "Loading model...",
        modelReady = "Model ready",
        modelErrorPrefix = "Model error: ",
        cameraPermissionDenied = "Camera permission denied",
        microphonePermissionDenied = "Microphone permission denied",
        responseLanguage = "App and response language",
        responseLanguageDescription = "Choose the language used for app text and model responses.",
        uiLanguageDescription = "Buttons, prompts, and model guidance follow this language.",
        model = "Model",
        filename = "Filename",
        installed = "Installed",
        size = "Size",
        path = "Path",
        pinnedSha = "Pinned SHA-256",
        noneVerificationSkipped = "(none - verification skipped)",
        stubModelActive = "Stub model active - Phase 2 swaps in LiteRT-LM",
        deleteModelFile = "Delete model file",
        about = "About",
        version = "Version",
        repository = "Repository",
        deleteModelTitle = "Delete model file?",
        deleteModelBody = "You’ll need to download the model again before running diagnostics.",
        delete = "Delete",
    )
}
